# Generated by Django 5.0.2 on 2024-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=64)),
                ('productDescription', models.TextField(max_length=64)),
                ('productManufactureInfo', models.CharField(max_length=64)),
                ('productSerialNumber', models.CharField(max_length=64, unique=True)),
                ('productDateManufacture', models.DateTimeField()),
                ('productWarrantyInfo', models.CharField(max_length=64)),
                ('productCategory', models.CharField(max_length=64)),
            ],
        ),
    ]
